### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Rikoshet-234** [joshuaskelly/io_scene_bsp#1]
Hello, when I try to activate the installed addon get an error 
![image](https://user-images.githubusercontent.com/34555340/54460356-9d6fd180-4769-11e9-8c89-5939cc50b48d.png)

**Comment by joshuaskelly** [comment]
As a workaround if you restart Blender you will be able to activate the addon. I will leave this issue open to investigate a better way of packaging my dependency.
