### ISSUE TITLE
Garry’s Mod import failure: buffer wrong size

### ISSUE THREAD

**Issue by thelabcat** [joshuaskelly/io_scene_bsp#6]
This was a mistake! Please close this issue. It is invalid.

**Comment by joshuaskelly** [comment]
No worries. Are you interested in importing Source bsp files?

**Comment by thelabcat** [comment]
Yes sir. Garry's Mod and Portal 2, particularly (I figure since GM and Portal are both HL2, if I ever wanted Portal maps I could do it if GM worked).

**Comment by thelabcat** [comment]
Incidentally, this ad on says the GM maps are not compatible with it.￼

**Comment by joshuaskelly** [comment]
Correct this addon only supports Quake bsp files.
